import type { Metadata } from "next";
import Link from "next/link";
import { TrendingUp, Zap, BarChart2, Shield, ArrowRight, Lock } from "lucide-react";
import { WaitlistForm } from "@/components/WaitlistForm";
import { WaitlistLeaderboard } from "@/components/WaitlistLeaderboard";

export const metadata: Metadata = {
  title: "Wealth Lab — AI Crypto & FX Trading Intelligence",
  description:
    "Join the exclusive early-access waitlist for MCKI Solutions' AI-powered Crypto and FX trading intelligence platform. Refer friends to move up the queue.",
};

const features = [
  {
    icon: Zap,
    title: "AI Signal Engine",
    desc: "Real-time buy/sell signals generated by machine learning models trained on years of market data.",
  },
  {
    icon: BarChart2,
    title: "Data Analysis Suite",
    desc: "Interactive dashboards for on-chain crypto data, FX flows, and macro sentiment — all in one view.",
  },
  {
    icon: Shield,
    title: "Risk Management AI",
    desc: "Automated position sizing, drawdown limits, and portfolio stress-testing.",
  },
  {
    icon: TrendingUp,
    title: "Strategy Backtester",
    desc: "Test any trading strategy against years of historical tick data before risking a single pound.",
  },
];

const tiers = [
  { position: "Top 100",   reward: "Founding Member — Free Early Access", color: "bg-gold-300 text-navy-500" },
  { position: "Top 500",   reward: "Early Bird — Priority Access",         color: "bg-navy-500 text-white" },
  { position: "Top 1,000", reward: "First Wave — Skip the Queue",          color: "bg-brand-alt text-navy-500 border border-brand-border" },
];

export default function TradingLabPage() {
  return (
    <>
      {/* ── HERO ── */}
      <section className="bg-hero-gradient text-white relative overflow-hidden">
        <div className="absolute inset-0 opacity-[0.04] dot-grid" />
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20 lg:py-28">
          <div className="max-w-3xl">
            <span className="badge bg-gold-300/20 text-gold-300 border border-gold-300/30 mb-4">
              Waitlist Now Open
            </span>
            <h1 className="text-4xl sm:text-5xl font-extrabold leading-tight tracking-tight mb-5">
              Stop Guessing.
              <span className="block text-gold-300">
                Start Trading with AI Intelligence.
              </span>
            </h1>
            <p className="text-lg text-white/80 leading-relaxed mb-8 max-w-2xl">
              MCKI Solutions&apos; Wealth Lab is an AI-powered trading intelligence
              platform for Crypto and FX markets — launching exclusively to early
              adopters. Join the waitlist and refer friends to unlock founding
              member access.
            </p>
            <a href="#waitlist" className="btn-primary">
              Claim My Spot <ArrowRight size={16} />
            </a>
          </div>
        </div>
      </section>

      {/* ── REWARD TIERS ── */}
      <section className="bg-brand-alt border-b border-brand-border py-12">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="section-heading text-xl text-center mb-8">
            Your Position. Your Reward.
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            {tiers.map((tier) => (
              <div
                key={tier.position}
                className={`rounded-2xl px-6 py-5 text-center ${tier.color}`}
              >
                <p className="font-heading font-bold text-lg">{tier.position}</p>
                <p className="text-sm mt-1 opacity-90">{tier.reward}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── FEATURES ── */}
      <section className="section-full bg-white">
        <div className="section">
          <div className="text-center mb-12">
            <p className="section-label mx-auto">Platform Features</p>
            <h2 className="section-heading text-3xl mb-3">
              What You&apos;re Getting Early Access To
            </h2>
            <div className="gold-bar mx-auto" />
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {features.map((feat) => (
              <div key={feat.title} className="card p-6 flex items-start gap-4">
                <div className="w-11 h-11 rounded-xl bg-navy-50 flex items-center justify-center flex-shrink-0">
                  <feat.icon size={20} className="text-navy-500" />
                </div>
                <div>
                  <h3 className="font-semibold text-navy-500 mb-2">{feat.title}</h3>
                  <p className="text-brand-muted text-sm leading-relaxed">{feat.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── WAITLIST FORM ── */}
      <section id="waitlist" className="section-full section-alt">
        <div className="section">
          <div className="max-w-xl mx-auto">
            <div className="text-center mb-10">
              <p className="section-label mx-auto">Join the Waitlist</p>
              <h2 className="section-heading text-3xl mb-3">Claim Your Spot</h2>
              <div className="gold-bar mx-auto" />
              <p className="answer-capsule mx-auto text-center mt-4">
                Every referral moves you higher in the queue. Share your unique
                link to unlock founding member access.
              </p>
            </div>
            <WaitlistForm />
          </div>
        </div>
      </section>

      {/* ── LEADERBOARD ── */}
      <section className="section-full bg-white">
        <div className="section">
          <div className="max-w-2xl mx-auto">
            <div className="text-center mb-10">
              <p className="section-label mx-auto">Live Leaderboard</p>
              <h2 className="section-heading text-3xl mb-3">Top Referrers</h2>
              <div className="gold-bar mx-auto" />
            </div>
            <WaitlistLeaderboard />
          </div>
        </div>
      </section>

      {/* ── RISK DISCLAIMER ── */}
      <section className="bg-brand-alt border-t border-brand-border py-8">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-start gap-3">
            <Lock size={14} className="text-brand-muted flex-shrink-0 mt-0.5" />
            <p className="text-brand-muted text-xs leading-relaxed">
              <strong>Risk Disclaimer:</strong> Trading in Crypto and FX markets
              involves significant risk of capital loss. The Wealth Lab provides
              AI-generated intelligence tools for informational and educational
              purposes only — not financial advice. Past performance is not
              indicative of future results. MCKI Solutions is not regulated by
              the FCA. Always seek independent financial advice before trading.
              Capital at risk.
            </p>
          </div>
        </div>
      </section>
    </>
  );
}
